const EX = [
{id:1,tier:1,title:"Declarar e imprimir",desc:"Declara dos variables a y b, asígnales valores e imprime ambas.",
 ref:`int main(){ int a=10; int b=20; cout<<a<<endl; cout<<b<<endl; return 0; }`},
{id:2,tier:1,title:"Suma de tres variables",desc:"Declara a, b y c. Asígnales valores y calcula su suma.",
 ref:`int main(){ int a=10; int b=20; int c=30; int suma=a+b+c; cout<<suma<<endl; return 0; }`},
{id:3,tier:1,title:"Intercambiar valores",desc:"Declara dos variables e intercambia sus valores usando una tercera variable auxiliar.",
 ref:`int main(){ int a=10; int b=20; int aux; aux=a; a=b; b=aux; cout<<a<<endl; cout<<b<<endl; return 0; }`},
{id:4,tier:1,title:"Promedio de 5 números",desc:"Declara 5 variables con diferentes números y calcula su promedio.",
 ref:`int main(){ int a=8; int b=9; int c=7; int d=10; int e=6; float promedio; promedio=(a+b+c+d+e)/5.0; cout<<promedio<<endl; return 0; }`},
{id:5,tier:1,title:"Tabla de multiplicar",desc:"Declara numero y muestra su tabla de multiplicar del 1 al 10 usando for.",
 ref:`int main(){ int numero=7; for(int i=1;i<=10;i++){ cout<<numero<<" x "<<i<<" = "<<numero*i<<endl; } return 0; }`},
{id:6,tier:1,title:"Contar hasta numero",desc:"Declara numero y usa for para imprimir los números del 1 hasta numero.",
 ref:`int main(){ int numero=10; for(int i=1;i<=numero;i++){ cout<<i<<endl; } return 0; }`},
{id:7,tier:1,title:"Cuenta regresiva",desc:"Usa for para imprimir los números del 10 al 1.",
 ref:`int main(){ for(int i=10;i>=1;i--){ cout<<i<<endl; } return 0; }`},
{id:8,tier:1,title:"Números pares",desc:"Usa for para imprimir únicamente los números pares del 1 al 20.",
 ref:`int main(){ for(int i=1;i<=20;i++){ if(i%2==0){ cout<<i<<endl; } } return 0; }`},
{id:9,tier:1,title:"Números impares",desc:"Usa for para imprimir únicamente los números impares del 1 al 20.",
 ref:`int main(){ for(int i=1;i<=20;i++){ if(i%2!=0){ cout<<i<<endl; } } return 0; }`},
{id:10,tier:1,title:"Suma del 1 al 100",desc:"Declara suma=0. Usa for para sumar los números del 1 al 100 y muestra el resultado.",
 ref:`int main(){ int suma=0; for(int i=1;i<=100;i++){ suma=suma+i; } cout<<suma<<endl; return 0; }`},
{id:11,tier:2,title:"Imprimir un vector",desc:"Declara un vector de 5 posiciones con 10,20,30,40,50. Imprime todos con for.",
 ref:`int main(){ int A[5]={10,20,30,40,50}; for(int i=0;i<5;i++){ cout<<A[i]<<endl; } return 0; }`},
{id:12,tier:2,title:"Llenar vector 1-10",desc:"Declara un vector de 10. Usa for para asignarle los números del 1 al 10 e imprímelos.",
 ref:`int main(){ int A[10]; for(int i=0;i<10;i++){ A[i]=i+1; } for(int i=0;i<10;i++){ cout<<A[i]<<endl; } return 0; }`},
{id:13,tier:2,title:"Vector de pares",desc:"Declara un vector de 10. Usa for para asignarle los pares del 2 al 20.",
 ref:`int main(){ int A[10]; for(int i=0;i<10;i++){ A[i]=(i+1)*2; } for(int i=0;i<10;i++){ cout<<A[i]<<endl; } return 0; }`},
{id:14,tier:2,title:"Vector de impares",desc:"Declara un vector de 10. Usa for para asignarle los impares del 1 al 19.",
 ref:`int main(){ int A[10]; for(int i=0;i<10;i++){ A[i]=(i*2)+1; } for(int i=0;i<10;i++){ cout<<A[i]<<endl; } return 0; }`},
{id:15,tier:2,title:"Copiar vector",desc:"Declara A[5] y B[5]. Asigna valores a A y copia todos sus valores a B con for.",
 ref:`int main(){ int A[5]={10,20,30,40,50}; int B[5]; for(int i=0;i<5;i++){ B[i]=A[i]; } for(int i=0;i<5;i++){ cout<<B[i]<<endl; } return 0; }`},
{id:16,tier:2,title:"Suma de un vector",desc:"Declara A[10] con 1..10 y calcula la suma de todos sus elementos con otro for.",
 ref:`int main(){ int A[10]; int suma=0; for(int i=0;i<10;i++){ A[i]=i+1; } for(int i=0;i<10;i++){ suma=suma+A[i]; } cout<<suma<<endl; return 0; }`},
{id:17,tier:2,title:"Vector al doble",desc:"Declara A[10] con valores y genera B[10] donde cada elemento sea el doble de A.",
 ref:`int main(){ int A[10]; int B[10]; for(int i=0;i<10;i++){ A[i]=i+1; } for(int i=0;i<10;i++){ B[i]=A[i]*2; } for(int i=0;i<10;i++){ cout<<B[i]<<endl; } return 0; }`},
{id:18,tier:2,title:"Vector al cuadrado",desc:"Genera B[10] donde cada elemento sea el cuadrado del correspondiente en A.",
 ref:`int main(){ int A[10]; int B[10]; for(int i=0;i<10;i++){ A[i]=i+1; } for(int i=0;i<10;i++){ B[i]=A[i]*A[i]; } for(int i=0;i<10;i++){ cout<<B[i]<<endl; } return 0; }`},
{id:19,tier:2,title:"Suma de dos vectores",desc:"Con A[5] y B[5], genera C[5] donde C[i] = A[i] + B[i].",
 ref:`int main(){ int A[5]={1,2,3,4,5}; int B[5]={10,20,30,40,50}; int C[5]; for(int i=0;i<5;i++){ C[i]=A[i]+B[i]; } for(int i=0;i<5;i++){ cout<<C[i]<<endl; } return 0; }`},
{id:20,tier:2,title:"Suma, promedio y pares",desc:"Recorre un vector de 10 y obtén la suma, el promedio y cuántos son pares.",
 ref:`int main(){ int A[10]={1,4,7,8,10,13,15,18,20,21}; int suma=0; int pares=0; float promedio; for(int i=0;i<10;i++){ suma=suma+A[i]; if(A[i]%2==0){ pares++; } } promedio=suma/10.0; cout<<"Suma: "<<suma<<endl; cout<<"Promedio: "<<promedio<<endl; cout<<"Pares: "<<pares<<endl; return 0; }`},
{id:21,tier:3,title:"Mayor y menor",desc:"Con un vector de 10, encuentra el número mayor y el número menor.",
 ref:`int main(){ int A[10]={15,8,23,4,19,7,31,2,12,10}; int mayor=A[0]; int menor=A[0]; for(int i=1;i<10;i++){ if(A[i]>mayor){ mayor=A[i]; } if(A[i]<menor){ menor=A[i]; } } cout<<"Mayor: "<<mayor<<endl; cout<<"Menor: "<<menor<<endl; return 0; }`},
{id:22,tier:3,title:"Positivos y negativos",desc:"Con un vector de 15, determina cuántos números son positivos y cuántos negativos.",
 ref:`int main(){ int A[15]={5,-2,8,-9,10,-4,7,-1,3,-6,12,-8,4,-3,15}; int positivos=0; int negativos=0; for(int i=0;i<15;i++){ if(A[i]>0){ positivos++; } if(A[i]<0){ negativos++; } } cout<<"Positivos: "<<positivos<<endl; cout<<"Negativos: "<<negativos<<endl; return 0; }`},
{id:23,tier:3,title:"Invertir vector",desc:"Con A[10] del 1 al 10, genera B[10] con los elementos en orden inverso.",
 ref:`int main(){ int A[10]={1,2,3,4,5,6,7,8,9,10}; int B[10]; for(int i=0;i<10;i++){ B[i]=A[9-i]; } for(int i=0;i<10;i++){ cout<<B[i]<<" "; } return 0; }`},
{id:24,tier:3,title:"Separar pares e impares",desc:"Con A[20], guarda los pares en P y los impares en I.",
 ref:`int main(){ int A[20]={1,5,8,10,13,16,21,24,27,30,33,36,40,43,46,50,53,56,60,63}; int P[20]; int I[20]; int cp=0; int ci=0; for(int i=0;i<20;i++){ if(A[i]%2==0){ P[cp]=A[i]; cp++; } else { I[ci]=A[i]; ci++; } } cout<<"Pares: "; for(int i=0;i<cp;i++){ cout<<P[i]<<" "; } cout<<endl; cout<<"Impares: "; for(int i=0;i<ci;i++){ cout<<I[i]<<" "; } return 0; }`},
{id:25,tier:3,title:"Rotar a la derecha",desc:"Con A[5]=1,2,3,4,5 genera B[5] desplazado una posición a la derecha: 5,1,2,3,4.",
 ref:`int main(){ int A[5]={1,2,3,4,5}; int B[5]; B[0]=A[4]; for(int i=1;i<5;i++){ B[i]=A[i-1]; } for(int i=0;i<5;i++){ cout<<B[i]<<" "; } return 0; }`},
{id:26,tier:3,title:"Rotar a la izquierda",desc:"Con A[5]=1,2,3,4,5 genera B[5] desplazado una posición a la izquierda: 2,3,4,5,1.",
 ref:`int main(){ int A[5]={1,2,3,4,5}; int B[5]; for(int i=0;i<4;i++){ B[i]=A[i+1]; } B[4]=A[0]; for(int i=0;i<5;i++){ cout<<B[i]<<" "; } return 0; }`},
{id:27,tier:3,title:"Comparar vectores",desc:"Determina si A[10] y B[10] tienen exactamente los mismos valores.",
 ref:`int main(){ int A[10]={1,2,3,4,5,6,7,8,9,10}; int B[10]={1,2,3,4,5,6,7,8,9,10}; int iguales=1; for(int i=0;i<10;i++){ if(A[i]!=B[i]){ iguales=0; } } if(iguales==1){ cout<<"Vectores iguales"; } else { cout<<"Vectores diferentes"; } return 0; }`},
{id:28,tier:3,title:"Eliminar una posición",desc:"Con A[5]=10,20,30,40,50 elimina la posición 2 y genera B[4]=10,20,40,50.",
 ref:`int main(){ int A[5]={10,20,30,40,50}; int B[4]; int j=0; for(int i=0;i<5;i++){ if(i!=2){ B[j]=A[i]; j++; } } for(int i=0;i<4;i++){ cout<<B[i]<<" "; } return 0; }`},
{id:29,tier:3,title:"Ordenar un vector",desc:"Ordena A[10]=8,3,5,1,9,2,7,4,6,0 de menor a mayor usando ciclos for.",
 ref:`int main(){ int A[10]={8,3,5,1,9,2,7,4,6,0}; int aux; for(int i=0;i<10;i++){ for(int j=i+1;j<10;j++){ if(A[i]>A[j]){ aux=A[i]; A[i]=A[j]; A[j]=aux; } } } for(int i=0;i<10;i++){ cout<<A[i]<<" "; } return 0; }`},
{id:30,tier:3,title:"Estadísticas completas",desc:"De un vector de 20, obtén suma, promedio, mayor, menor, pares, impares, positivos y negativos.",
 ref:`int main(){ int A[20]={5,-2,8,15,-7,10,3,-4,12,6,-9,20,11,-1,7,14,-6,2,18,-3}; int suma=0; int mayor=A[0]; int menor=A[0]; int pares=0; int impares=0; int positivos=0; int negativos=0; float promedio; for(int i=0;i<20;i++){ suma=suma+A[i]; if(A[i]>mayor){ mayor=A[i]; } if(A[i]<menor){ menor=A[i]; } if(A[i]%2==0){ pares++; } else { impares++; } if(A[i]>0){ positivos++; } if(A[i]<0){ negativos++; } } promedio=suma/20.0; cout<<"Suma: "<<suma<<endl<<"Promedio: "<<promedio<<endl<<"Mayor: "<<mayor<<endl<<"Menor: "<<menor<<endl<<"Pares: "<<pares<<endl<<"Impares: "<<impares<<endl<<"Positivos: "<<positivos<<endl<<"Negativos: "<<negativos<<endl; return 0; }`},
];

const TIER_META = {
  1:{emoji:"🟢",cls:"avail-g",badge:'bg-[var(--green)] text-black',label:'NIVEL 1'},
  2:{emoji:"🟡",cls:"avail-y",badge:'bg-[var(--yellow)] text-black',label:'NIVEL 2'},
  3:{emoji:"🔴",cls:"avail-r",badge:'bg-[var(--red)] text-black',label:'NIVEL 3'}
};
